// samplesites/6-vue3-nuxt3/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';

const patientId = ref('pt_metro_8841');
const selectedDepartment = ref('Cardiology');
</script>

<template>
  <div style="max-width: 1100px; margin: 0 auto; padding: 40px 24px;">
    <header style="display: flex; justify-content: space-between; align-items: center; padding-bottom: 24px; border-bottom: 1px solid rgba(255,255,255,0.08); margin-bottom: 36px;">
      <div style="font-size: 20px; font-weight: 800; display: flex; align-items: center; gap: 8px;">
        🏥 MetroHealth Patient Portal
      </div>
      <div style="font-size: 13px; color: #a1a1aa;">
        Patient ID: {{ patientId }}
      </div>
    </header>

    <main>
      <div style="background: #121215; border: 1px solid rgba(255,255,255,0.08); border-radius: 16px; padding: 36px; margin-bottom: 32px;">
        <h1 style="font-size: 28px; font-weight: 800; margin-bottom: 12px;">Diagnostic Lab &amp; Follow-up Consultations</h1>
        <p style="color: #a1a1aa; font-size: 15px; margin: 0;">
          Schedule outpatient appointments, check fasting preparation guidelines, and view digital lab reports.
        </p>
      </div>

      <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px;">
        <div style="background: #121215; border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 24px;">
          <div style="font-size: 12px; color: #4ade80; font-weight: 700; text-transform: uppercase;">Upcoming Appointment</div>
          <div style="font-size: 18px; font-weight: 700; color: #ffffff; margin: 8px 0;">Routine Cardiology Review</div>
          <div style="font-size: 13px; color: #a1a1aa;">Dr. Sarah Jenkins &bull; Thursday at 10:30 AM</div>
        </div>

        <div style="background: #121215; border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 24px;">
          <div style="font-size: 12px; color: #38bdf8; font-weight: 700; text-transform: uppercase;">Insurance Coverage</div>
          <div style="font-size: 18px; font-weight: 700; color: #ffffff; margin: 8px 0;">BlueCross BlueShield</div>
          <div style="font-size: 13px; color: #22c55e;">Active &bull; Standard In-Network Co-Pay</div>
        </div>
      </div>
    </main>

    <!-- ================================================================= -->
    <!-- 🔌 PASTE YOUR VUE COMPONENT OR EMBED WIDGET HERE                    -->
    <!-- (Generate from Agent Studio -> Embed Code -> Vue Export)           -->
    <!-- ================================================================= -->
  </div>
</template>

// samplesites/5-angular-ts/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: []
})
export class AppComponent {
  title = 'Apex Institute Student ERP';
}

<div style="max-width: 1100px; margin: 0 auto; padding: 40px 24px;">
  <header style="display: flex; justify-content: space-between; align-items: center; padding-bottom: 24px; border-bottom: 1px solid rgba(255,255,255,0.08); margin-bottom: 36px;">
    <div style="font-size: 20px; font-weight: 800; display: flex; align-items: center; gap: 8px;">
      🎓 Apex Institute Student ERP
    </div>
    <div style="font-size: 13px; color: #a1a1aa;">
      Academic Year: 2026-2027
    </div>
  </header>

  <main>
    <div style="background: #121215; border: 1px solid rgba(255,255,255,0.08); border-radius: 16px; padding: 36px; margin-bottom: 32px;">
      <h1 style="font-size: 28px; font-weight: 800; margin-bottom: 12px;">Semester 6 Enrollment &amp; Attendance Portal</h1>
      <p style="color: #a1a1aa; font-size: 15px; margin: 0;">Access attendance records, internal assessment scores, hostel leave passes, and placement drive eligibility.</p>
    </div>

    <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px;">
      <div style="background: #121215; border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 24px;">
        <div style="font-size: 12px; color: #38bdf8; font-weight: 700; text-transform: uppercase;">Aggregate Attendance</div>
        <div style="font-size: 32px; font-weight: 800; color: #22c55e; margin: 10px 0;">88.5%</div>
        <div style="font-size: 12px; color: #a1a1aa;">Eligible for End-Sem Exams (Min 75%)</div>
      </div>

      <div style="background: #121215; border: 1px solid rgba(255,255,255,0.08); border-radius: 12px; padding: 24px;">
        <div style="font-size: 12px; color: #c084fc; font-weight: 700; text-transform: uppercase;">Cumulative CGPA</div>
        <div style="font-size: 32px; font-weight: 800; color: #ffffff; margin: 10px 0;">8.92</div>
        <div style="font-size: 12px; color: #22c55e;">Qualified for Dream Placement Drives</div>
      </div>
    </div>
  </main>

  <!-- ================================================================= -->
  <!-- 🔌 PASTE YOUR ANGULAR COMPONENT OR EMBED WIDGET HERE                -->
  <!-- (Generate from Agent Studio -> Embed Code -> Angular Export)       -->
  <!-- ================================================================= -->
</div>
